services:
  - type: web
    name: mentorscue
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mentorscue-db
          property: connectionString

databases:
  - name: mentorscue-db
    plan: free
    databaseName: mentorscue
    user: mentorscue_user